name: Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - package.json
      - README.md
      - '.dependabot/**'
      - .editorconfig
      - .gitignore
      - .npmignore
      - .npmrc
      - .nvmrc
      - .nycrc
  pull_request:
    branches:
      - master
    paths-ignore:
      - package.json
      - README.md
      - '.dependabot/**'
      - .editorconfig
      - .gitignore
      - .npmignore
      - .npmrc
      - .nvmrc
      - .nycrc
jobs:
  build:
    name: Build octopus-deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10
          - 12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules ${{ matrix.node-version }}
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:ci
